### ISSUE TITLE
HW4: More info

### ISSUE THREAD

**Issue by MattyAyOh** [drwecker/StockPrices#10]
- Display time searched (see #8)
- Display percentage change
- Display trade volume
- If a ticker is submitted that already exists in the table, replace it
- When the window's size changes, make the table's size change with it 
- Add another text field & button combo to remove tickers.  
- Enter key should submit ticker

**Due Friday August 19th, 11:59PM**

**40 points**

**Comment by MattyAyOh** [comment]
@drwecker

**Comment by drwecker** [comment]
I think we're in pretty good shape on these requirements.  There were a couple of slight differences.  I used the same text field for add or delete a row in the table.  I also went with the last trade time instead of the time searched just because it seems more relevant to what the actual price is showing.

**Comment by MattyAyOh** [comment]
With time to spare 👍  
I'll check this out later on my windows machine

**Comment by MattyAyOh** [comment]
**34/40 Points**

Quotes are left in the change and last trade columns (-1 point)
Resizing vertically does nothing (-5 points)

Side note, you should make the stock tickers capitalized
